# Site settings
title: Coding With Wing
email: findmeongithub
description: > # this means to ignore newlines until "baseurl:"
  Wing's blog site of his thoughts and coding experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://winghymliu.github.io" # the base hostname & protocol for your site
twitter_username: borlorbao
github_username:  winghymliu

# Build settings
markdown: kramdown
